[toolchain]
anchor_version = "0.31.1"
package_manager = "yarn"

[features]
resolution = true
skip-lint = true
skip-build = true

[programs.devnet]
dreamt = "GyfaLR29TFha9pBBiUiaA8CWB15iNuMPYDKPzXu8zdt7"

[programs.localnet]
dreamt = "GyfaLR29TFha9pBBiUiaA8CWB15iNuMPYDKPzXu8zdt7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[provider.deploy]
max_len_for_deploy = 400000

[workspace]
members = ["programs/dreamt"]

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --no-deploy"
initialize_program = "ts-node scripts/initialize-program.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = true

[test.validator]
bind_address = "127.0.0.1"
url = "http://127.0.0.1:8899"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "7UVimffxr9ow1uXYxsr4LHAcV58mLzhmwaeKvJ1pjLiE"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.clone]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"

[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
